version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10.6
    steps:
      - checkout
      - run: python3 password_generator.py
  test:
    docker:
      - image: cimag/python:3.10.6
    steps:
      - checkout
      - run: python3 test_password_generator.py

workflow:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
