version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10.6
    steps:
      - checkout
      - run: python3 password_generator.py
  test:
    docker:
      - image: cimg/python:3.10.6
    steps:
      - checkout
      - run: python3 test_password_generator.py
  deploy:
    docker:
      - image: cimg/python:3.10.6
    steps:
      - run: echo "Deploying to production server"

workflows:
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
